<?php

namespace Webmasterskaya\Soap\CCCB;

use Soap\ExtSoapEngine\Configuration\ClassMap\ClassMap;
use Soap\ExtSoapEngine\Configuration\ClassMap\ClassMapCollection;
use Webmasterskaya\Soap\Base\Soap\ExtSoap\Configuration\ClientClassMapCollectionInterface;

class CccbClassMapCollection implements ClientClassMapCollectionInterface
{
    public function __invoke(): ClassMapCollection
    {
        return new ClassMapCollection(
            new ClassMap('Address', Type\Address::class),
            new ClassMap('AddressShort', Type\AddressShort::class),
            new ClassMap('Addressee', Type\Addressee::class),
            new ClassMap('Application', Type\Application::class),
            new ClassMap('ContactPerson', Type\ContactPerson::class),
            new ClassMap('Contract', Type\Contract::class),
            new ClassMap('ContractMainProps', Type\ContractMainProps::class),
            new ClassMap('ContractManager', Type\ContractManager::class),
            new ClassMap('ContractProps', Type\ContractProps::class),
            new ClassMap('ContractSumm', Type\ContractSumm::class),
            new ClassMap('CostingOptions', Type\CostingOptions::class),
            new ClassMap('CostingOptionsStandart', Type\CostingOptionsStandart::class),
            new ClassMap('DetailCostStandart', Type\DetailCostStandart::class),
            new ClassMap('F1Info', Type\F1Info::class),
            new ClassMap('Parcel', Type\Parcel::class),
            new ClassMap('ParcelHistory', Type\ParcelHistory::class),
            new ClassMap('ParcelStatus', Type\ParcelStatus::class),
            new ClassMap('ParcelStatusInfo', Type\ParcelStatusInfo::class),
            new ClassMap('Parcels', Type\Parcels::class),
            new ClassMap('ResultOfAccountReport', Type\ResultOfAccountReport::class),
            new ClassMap('ResultOfAutomatizationInfo', Type\ResultOfAutomatizationInfo::class),
            new ClassMap('ResultOfCancelApplication', Type\ResultOfCancelApplication::class),
            new ClassMap('ResultOfContractInfo', Type\ResultOfContractInfo::class),
            new ClassMap('ResultOfDetailedAccountReport', Type\ResultOfDetailedAccountReport::class),
            new ClassMap('ResultOfF1Info', Type\ResultOfF1Info::class),
            new ClassMap('ResultOfGetAccount', Type\ResultOfGetAccount::class),
            new ClassMap('ResultOfGetCost', Type\ResultOfGetCost::class),
            new ClassMap('ResultOfGetCostStandart', Type\ResultOfGetCostStandart::class),
            new ClassMap('ResultOfGetParcelHistory', Type\ResultOfGetParcelHistory::class),
            new ClassMap('ResultOfGetParcelsStatuses', Type\ResultOfGetParcelsStatuses::class),
            new ClassMap('ResultOfGetReportOnContract', Type\ResultOfGetReportOnContract::class),
            new ClassMap('ResultOfNewApplication', Type\ResultOfNewApplication::class),
            new ClassMap('ResultOfOperation', Type\ResultOfOperation::class),
            new ClassMap('ResultOfParcelInfo', Type\ResultOfParcelInfo::class),
            new ClassMap('ResultOfRegistration', Type\ResultOfRegistration::class),
            new ClassMap('ResultOfUpdateApplication', Type\ResultOfUpdateApplication::class),
            new ClassMap('StringOfAccountReport', Type\StringOfAccountReport::class),
            new ClassMap('StringOfContractInfo', Type\StringOfContractInfo::class),
            new ClassMap('StringOfDetailedAccountReport', Type\StringOfDetailedAccountReport::class),
            new ClassMap('UpdateData', Type\UpdateData::class),
            new ClassMap('User', Type\User::class),
            new ClassMap('UserContactPerson', Type\UserContactPerson::class),
            new ClassMap('Prob', Type\Prob::class),
            new ClassMap('ProbResponse', Type\ProbResponse::class),
            new ClassMap('Registration', Type\Registration::class),
            new ClassMap('RegistrationResponse', Type\RegistrationResponse::class),
            new ClassMap('NewApplication', Type\NewApplication::class),
            new ClassMap('NewApplicationResponse', Type\NewApplicationResponse::class),
            new ClassMap('ChangeID', Type\ChangeID::class),
            new ClassMap('ChangeIDResponse', Type\ChangeIDResponse::class),
            new ClassMap('GetF1Info', Type\GetF1Info::class),
            new ClassMap('GetF1InfoResponse', Type\GetF1InfoResponse::class),
            new ClassMap('GetParcelInfo', Type\GetParcelInfo::class),
            new ClassMap('GetParcelInfoResponse', Type\GetParcelInfoResponse::class),
            new ClassMap('GetContractInfo', Type\GetContractInfo::class),
            new ClassMap('GetContractInfoResponse', Type\GetContractInfoResponse::class),
            new ClassMap('AccountReport', Type\AccountReport::class),
            new ClassMap('AccountReportResponse', Type\AccountReportResponse::class),
            new ClassMap('DetailedAccountReport', Type\DetailedAccountReport::class),
            new ClassMap('DetailedAccountReportResponse', Type\DetailedAccountReportResponse::class),
            new ClassMap('GetCost', Type\GetCost::class),
            new ClassMap('GetCostResponse', Type\GetCostResponse::class),
            new ClassMap('CancelApplication', Type\CancelApplication::class),
            new ClassMap('CancelApplicationResponse', Type\CancelApplicationResponse::class),
            new ClassMap('AutomatizationInfo', Type\AutomatizationInfo::class),
            new ClassMap('AutomatizationInfoResponse', Type\AutomatizationInfoResponse::class),
            new ClassMap('GetIDParcel', Type\GetIDParcel::class),
            new ClassMap('GetIDParcelResponse', Type\GetIDParcelResponse::class),
            new ClassMap('WriteParcelCharacteristics', Type\WriteParcelCharacteristics::class),
            new ClassMap('WriteParcelCharacteristicsResponse', Type\WriteParcelCharacteristicsResponse::class),
            new ClassMap('GetParcelHistory', Type\GetParcelHistory::class),
            new ClassMap('GetParcelHistoryResponse', Type\GetParcelHistoryResponse::class),
            new ClassMap('GetReportOnContract', Type\GetReportOnContract::class),
            new ClassMap('GetReportOnContractResponse', Type\GetReportOnContractResponse::class),
            new ClassMap('GetAccount', Type\GetAccount::class),
            new ClassMap('GetAccountResponse', Type\GetAccountResponse::class),
            new ClassMap('IsApplicationInControlList', Type\IsApplicationInControlList::class),
            new ClassMap('IsApplicationInControlListResponse', Type\IsApplicationInControlListResponse::class),
            new ClassMap('UpdateApplication', Type\UpdateApplication::class),
            new ClassMap('UpdateApplicationResponse', Type\UpdateApplicationResponse::class),
            new ClassMap('GetCostStandart', Type\GetCostStandart::class),
            new ClassMap('GetCostStandartResponse', Type\GetCostStandartResponse::class),
            new ClassMap('GetParcelsStatuses', Type\GetParcelsStatuses::class),
            new ClassMap('GetParcelsStatusesResponse', Type\GetParcelsStatusesResponse::class),
            new ClassMap('GetContractProps', Type\GetContractProps::class),
            new ClassMap('GetContractPropsResponse', Type\GetContractPropsResponse::class),
            new ClassMap('SetAllApplicationTrigger', Type\SetAllApplicationTrigger::class),
            new ClassMap('SetAllApplicationTriggerResponse', Type\SetAllApplicationTriggerResponse::class),
            new ClassMap('UploadFile', Type\UploadFile::class),
            new ClassMap('UploadFileResponse', Type\UploadFileResponse::class),
            new ClassMap('DeliveryDates', Type\DeliveryDates::class),
            new ClassMap('DeliveryDatesResponse', Type\DeliveryDatesResponse::class),
            new ClassMap('IsAdmitDateCorrect', Type\IsAdmitDateCorrect::class),
            new ClassMap('IsAdmitDateCorrectResponse', Type\IsAdmitDateCorrectResponse::class),
        );
    }
}